"""initial schema

Revision ID: 3becbeae2d4e
Revises: 
Create Date: 2026-04-20 15:10:12.283537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3becbeae2d4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entites_juridiques',
    sa.Column('nofinesset', sa.String(length=9), nullable=False),
    sa.Column('rs', sa.String(length=255), nullable=True, comment='Raison sociale'),
    sa.Column('rslongue', sa.Text(), nullable=True, comment='Raison sociale longue'),
    sa.Column('categetab', sa.String(length=4), nullable=True, comment='Code catégorie'),
    sa.Column('libcategetab', sa.String(length=255), nullable=True, comment='Libellé catégorie'),
    sa.Column('numvoie', sa.String(length=10), nullable=True),
    sa.Column('typvoie', sa.String(length=10), nullable=True),
    sa.Column('voie', sa.String(length=255), nullable=True),
    sa.Column('compvoie', sa.String(length=255), nullable=True),
    sa.Column('compldistrib', sa.String(length=255), nullable=True),
    sa.Column('codepostal', sa.String(length=5), nullable=True),
    sa.Column('commune', sa.String(length=5), nullable=True, comment='Code commune INSEE'),
    sa.Column('libcommune', sa.String(length=255), nullable=True),
    sa.Column('departement', sa.String(length=3), nullable=True),
    sa.Column('libdepartement', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=2), nullable=True, comment='Code région'),
    sa.Column('libregion', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('telecopie', sa.String(length=20), nullable=True),
    sa.Column('courriel', sa.String(length=255), nullable=True),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('dateouv', sa.String(length=10), nullable=True, comment="Date d'ouverture"),
    sa.Column('dateautor', sa.String(length=10), nullable=True, comment="Date d'autorisation"),
    sa.PrimaryKeyConstraint('nofinesset')
    )
    op.create_index(op.f('ix_entites_juridiques_nofinesset'), 'entites_juridiques', ['nofinesset'], unique=False)
    op.create_table('historique_modifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entite_type', sa.String(length=2), nullable=True, comment='ET ou EJ'),
    sa.Column('nofinesset', sa.String(length=9), nullable=True),
    sa.Column('champ', sa.String(length=50), nullable=True),
    sa.Column('ancienne_valeur', sa.Text(), nullable=True),
    sa.Column('nouvelle_valeur', sa.Text(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True, comment='import, manuel, reconciliation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historique_modifications_nofinesset'), 'historique_modifications', ['nofinesset'], unique=False)
    op.create_table('etablissements',
    sa.Column('nofinesset', sa.String(length=9), nullable=False),
    sa.Column('nofinessej', sa.String(length=9), nullable=True),
    sa.Column('rs', sa.String(length=255), nullable=True, comment='Raison sociale'),
    sa.Column('rslongue', sa.Text(), nullable=True, comment='Raison sociale longue'),
    sa.Column('categetab', sa.String(length=4), nullable=True, comment='Code catégorie'),
    sa.Column('libcategetab', sa.String(length=255), nullable=True, comment='Libellé catégorie'),
    sa.Column('categagretab', sa.String(length=4), nullable=True, comment='Code catégorie agrégée'),
    sa.Column('libcategagretab', sa.String(length=255), nullable=True, comment='Libellé catégorie agrégée'),
    sa.Column('numvoie', sa.String(length=10), nullable=True),
    sa.Column('typvoie', sa.String(length=10), nullable=True),
    sa.Column('voie', sa.String(length=255), nullable=True),
    sa.Column('compvoie', sa.String(length=255), nullable=True),
    sa.Column('compldistrib', sa.String(length=255), nullable=True),
    sa.Column('codepostal', sa.String(length=5), nullable=True),
    sa.Column('commune', sa.String(length=5), nullable=True, comment='Code commune INSEE'),
    sa.Column('libcommune', sa.String(length=255), nullable=True),
    sa.Column('departement', sa.String(length=3), nullable=True),
    sa.Column('libdepartement', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=2), nullable=True, comment='Code région'),
    sa.Column('libregion', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('telecopie', sa.String(length=20), nullable=True),
    sa.Column('courriel', sa.String(length=255), nullable=True),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('dateouv', sa.String(length=10), nullable=True, comment="Date d'ouverture"),
    sa.Column('dateautor', sa.String(length=10), nullable=True, comment="Date d'autorisation"),
    sa.Column('mft', sa.String(length=4), nullable=True, comment='Code mode de fixation des tarifs'),
    sa.Column('libmft', sa.String(length=255), nullable=True, comment='Libellé MFT'),
    sa.Column('sph', sa.String(length=4), nullable=True, comment='Code SPH'),
    sa.Column('libsph', sa.String(length=255), nullable=True, comment='Libellé SPH'),
    sa.Column('coordxet', sa.String(length=20), nullable=True, comment='Coordonnée X (Lambert 93)'),
    sa.Column('coordyet', sa.String(length=20), nullable=True, comment='Coordonnée Y (Lambert 93)'),
    sa.ForeignKeyConstraint(['nofinessej'], ['entites_juridiques.nofinesset'], ),
    sa.PrimaryKeyConstraint('nofinesset')
    )
    op.create_index(op.f('ix_etablissements_nofinessej'), 'etablissements', ['nofinessej'], unique=False)
    op.create_index(op.f('ix_etablissements_nofinesset'), 'etablissements', ['nofinesset'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nofinesset', sa.String(length=9), nullable=True),
    sa.Column('nofinessej', sa.String(length=9), nullable=True),
    sa.Column('regle', sa.String(length=50), nullable=False, comment='Identifiant de la règle'),
    sa.Column('niveau', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('date_detection', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['nofinesset'], ['etablissements.nofinesset'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_nofinesset'), 'anomalies', ['nofinesset'], unique=False)
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nofinesset', sa.String(length=9), nullable=True),
    sa.Column('nofinessej', sa.String(length=9), nullable=True),
    sa.Column('type_demande', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('objet', sa.Text(), nullable=True, comment='Description de la demande'),
    sa.Column('demandeur', sa.String(length=255), nullable=True),
    sa.Column('agent_instructeur', sa.String(length=255), nullable=True),
    sa.Column('date_reception', sa.DateTime(), nullable=True),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('date_cloture', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nofinesset'], ['etablissements.nofinesset'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_nofinesset'), 'dossiers', ['nofinesset'], unique=False)
    op.create_table('evenements_dossier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('auteur', sa.String(length=255), nullable=True),
    sa.Column('type_evenement', sa.String(length=50), nullable=True, comment='changement_statut, commentaire, piece_jointe'),
    sa.Column('ancien_statut', sa.String(length=20), nullable=True),
    sa.Column('nouveau_statut', sa.String(length=20), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('piece_jointe', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evenements_dossier_dossier_id'), 'evenements_dossier', ['dossier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evenements_dossier_dossier_id'), table_name='evenements_dossier')
    op.drop_table('evenements_dossier')
    op.drop_index(op.f('ix_dossiers_nofinesset'), table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index(op.f('ix_anomalies_nofinesset'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_etablissements_nofinesset'), table_name='etablissements')
    op.drop_index(op.f('ix_etablissements_nofinessej'), table_name='etablissements')
    op.drop_table('etablissements')
    op.drop_index(op.f('ix_historique_modifications_nofinesset'), table_name='historique_modifications')
    op.drop_table('historique_modifications')
    op.drop_index(op.f('ix_entites_juridiques_nofinesset'), table_name='entites_juridiques')
    op.drop_table('entites_juridiques')
    # ### end Alembic commands ###
